name: Validate PR Source

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.base_ref }}" != "dev" ]]; then
            echo "Pull requests to main can only originate from dev branch."
            exit 1
          fi
